import { Button, Card, DatePicker, Empty, Select, Space, Table, Tag, Typography } from 'antd'
import type { ColumnsType } from 'antd/es/table'
import dayjs, { type Dayjs } from 'dayjs'
import { useCallback, useEffect, useMemo, useState } from 'react'
import { Link, useNavigate, useSearchParams } from 'react-router-dom'
import type { OrgOption, ReportCadence, ReportListItem } from '../api'
import { api } from '../api'
import { TitleWithHelp } from '../components/HelpTip'
import { LoadError } from '../components/LoadError'
import { useAuth } from '../auth'
import { useIsMobile } from '../layout/useIsMobile'

export function ReportsPage() {
  const { user } = useAuth()
  const navigate = useNavigate()
  const [searchParams, setSearchParams] = useSearchParams()
  const isMobile = useIsMobile()
  const [orgs, setOrgs] = useState<OrgOption[]>([])
  const [orgId, setOrgId] = useState<string | undefined>(() => searchParams.get('organizationId') ?? undefined)
  const [cadence, setCadence] = useState<ReportCadence>('Monthly')
  const [month, setMonth] = useState<Dayjs>(dayjs('2026-09-01'))
  const [year, setYear] = useState<Dayjs>(dayjs('2026-01-01'))
  const [rows, setRows] = useState<ReportListItem[]>([])
  const [loading, setLoading] = useState(true)
  const [generating, setGenerating] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const canGenerate = !!user?.canMutateWorkItems

  const loadOrgs = useCallback(async () => {
    try {
      const list = await api.organizations()
      setOrgs(list)
      setOrgId((current) => {
        if (current && list.some((org) => org.id === current)) return current
        return list[0]?.id
      })
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Could not load organizations.')
    }
  }, [])

  const selectOrg = (id: string) => {
    setOrgId(id)
    setSearchParams({ organizationId: id }, { replace: true })
  }

  useEffect(() => {
    if (orgId && searchParams.get('organizationId') !== orgId) {
      setSearchParams({ organizationId: orgId }, { replace: true })
    }
  }, [orgId, searchParams, setSearchParams])

  const load = useCallback(async () => {
    setLoading(true)
    setError(null)
    try {
      setRows(await api.reports(orgId))
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Reports failed to load.')
    } finally {
      setLoading(false)
    }
  }, [orgId])

  useEffect(() => {
    void loadOrgs()
  }, [loadOrgs])

  useEffect(() => {
    if (orgId || orgs.length === 0) {
      void load()
    }
  }, [load, orgId, orgs.length])

  const generate = async () => {
    if (!orgId) return
    setGenerating(true)
    setError(null)
    try {
      const report = cadence === 'Annual'
        ? await api.generateReport(orgId, 'Annual', year.year())
        : await api.generateReport(orgId, 'Monthly', month.year(), month.month() + 1)
      navigate(`/reports/${report.id}`)
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Could not generate the report.')
    } finally {
      setGenerating(false)
    }
  }

  const columns: ColumnsType<ReportListItem> = useMemo(() => [
    {
      title: 'Period',
      dataIndex: 'monthLabel',
      render: (label: string, row) => <Link to={`/reports/${row.id}`}>{label}</Link>,
    },
    {
      title: 'Cadence',
      dataIndex: 'cadence',
      width: 110,
      render: (value: string) => <Tag color={value === 'Annual' ? 'purple' : 'blue'}>{value || 'Monthly'}</Tag>,
    },
    { title: 'Client', dataIndex: 'organizationName', responsive: ['md'] },
    { title: 'Version', dataIndex: 'version', width: 90, responsive: ['sm'] },
    {
      title: 'Generated',
      dataIndex: 'generatedAt',
      render: (value: string) => dayjs(value).format('YYYY-MM-DD HH:mm'),
    },
    { title: 'Generated by', dataIndex: 'generatedByName', responsive: ['lg'] },
    {
      title: 'Emailed',
      key: 'emailed',
      render: (_, row) => row.emailed
        ? <Tag color="green">Sent {dayjs(row.lastEmailedAt).format('YYYY-MM-DD')}</Tag>
        : <Tag>Not emailed</Tag>,
    },
  ], [])

  return (
    <Space direction="vertical" size={8} style={{ width: '100%' }}>
      <div>
        <Typography.Title level={3} className="page-title" style={{ margin: 0 }}>
          <TitleWithHelp
            help={
              canGenerate
                ? 'Per-client GIS Maintenance Report — monthly (parcel status + month completed items) or annual (year totals + completed-item listing). Generating again adds a new version. Administrators and Editors can generate, download PDF/CSV, and email. Viewers can read and download.'
                : 'Per-client GIS Maintenance Report. You can read and download reports for your organization. Ask an Editor or Administrator to generate or email one.'
            }
          >
            GIS Maintenance Reports
          </TitleWithHelp>
        </Typography.Title>
      </div>

      <Card className="compact-card bis-theme-panel">
        <div className="filter-toolbar">
          <Select
            placeholder="Client"
            className="filter-field"
            value={orgId}
            onChange={selectOrg}
            options={orgs.map((o) => ({ value: o.id, label: o.name }))}
          />
          {canGenerate && (
            <>
              <Select
                value={cadence}
                onChange={setCadence}
                className="filter-field-sm"
                options={[
                  { value: 'Monthly', label: 'Monthly' },
                  { value: 'Annual', label: 'Annual' },
                ]}
              />
              {cadence === 'Annual' ? (
                <DatePicker
                  picker="year"
                  value={year}
                  onChange={(value) => value && setYear(value)}
                  allowClear={false}
                  className="filter-field-sm"
                />
              ) : (
                <DatePicker
                  picker="month"
                  value={month}
                  onChange={(value) => value && setMonth(value)}
                  allowClear={false}
                  className="filter-field"
                />
              )}
              <Button type="primary" loading={generating} disabled={!orgId} onClick={() => void generate()}>
                Generate {cadence === 'Annual' ? 'year' : 'month'}
              </Button>
            </>
          )}
        </div>
      </Card>

      {error && <LoadError message={error} onRetry={() => void load()} />}

      {isMobile ? (
        <Space direction="vertical" size={8} style={{ width: '100%' }}>
          {loading && <Card className="bis-theme-panel" loading />}
          {!loading && rows.length === 0 && (
            <Card className="bis-theme-panel">
              <Empty description={canGenerate
                ? 'No reports yet. Generate a month or year to snapshot completed maintenance.'
                : 'No reports yet for this client. Ask an Editor or Administrator to generate one.'} />
            </Card>
          )}
          {rows.map((row) => (
            <Card key={row.id} size="small" hoverable className="bis-theme-panel" onClick={() => navigate(`/reports/${row.id}`)}>
              <Typography.Text strong>{row.monthLabel}</Typography.Text>
              <div>
                <Tag color={row.cadence === 'Annual' ? 'purple' : 'blue'}>{row.cadence || 'Monthly'}</Tag>
                <Typography.Text type="secondary">{row.organizationName} · v{row.version}</Typography.Text>
              </div>
              <div>
                <Typography.Text type="secondary">
                  Generated {dayjs(row.generatedAt).format('YYYY-MM-DD HH:mm')}
                </Typography.Text>
              </div>
              {row.emailed
                ? <Tag color="green">Last emailed {dayjs(row.lastEmailedAt).format('YYYY-MM-DD')}</Tag>
                : <Tag>Not emailed</Tag>}
            </Card>
          ))}
        </Space>
      ) : (
        <Card title="History" className="bis-theme-panel">
          <Table
            rowKey="id"
            className="bis-theme-grid"
            size="small"
            loading={loading}
            dataSource={rows}
            columns={columns}
            locale={{
              emptyText: canGenerate
                ? 'No reports yet. Generate a month or year to snapshot completed maintenance.'
                : 'No reports yet for this client.',
            }}
            onRow={(row) => ({
              onClick: () => navigate(`/reports/${row.id}`),
              style: { cursor: 'pointer' },
            })}
            pagination={{ pageSize: 12, hideOnSinglePage: true }}
          />
        </Card>
      )}
    </Space>
  )
}
